name: Setup pnpm

description: "Installs Node.js and pnpm, and caches the pnpm store directory to speed up future runs."

inputs:
  pnpm-version:
    description: "pnpm version"
    required: true
    default: "latest"

# https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile --strict-peer-dependencies
