name: Lint

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  typecheck:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: "./.github/actions/setup-pnpm"

      - name: Build
        run: pnpm build
        env:
          BASE_URL: ${{ github.event.repository.name }}

      - name: Type check
        run: pnpm typecheck
