name: Verify

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: "./.github/actions/setup-pnpm"

      - name: Build
        run: pnpm build
        env:
          BASE_URL: ${{ github.event.repository.name }}

      - name: Verify TypeScript types
        run: pnpm typecheck

      - name: Check for linting errors
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test
